# Generated by Django 4.2.1 on 2023-05-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Books&Sports', 'Books&Sports'), ('Cars', 'Cars'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Property', 'Property')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MI', 'Sikkim'), ('ML', 'Meghalaya'), ('GA', 'Goa'), ('AS', 'Assam'), ('CG', 'Chhattisgarh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('WB', 'West Bengal'), ('GJ', 'Gujarat'), ('MP', 'Madhya Pradesh'), ('TN', 'Tamil Nadu'), ('AR', 'Arunachal Pradesh'), ('MN', 'Manipur'), ('NL', 'Nagaland'), ('KL', 'Kerala'), ('UK', 'Uttarakhand'), ('MH', 'Maharashtra'), ('PB', 'Punjab'), ('TS', 'Telangana'), ('UP', 'Uttar Pradesh'), ('RJ', 'Rajasthan'), ('HP', 'Haryana'), ('OD', 'Odisha'), ('BR', 'Bihar'), ('MZ', 'Mizoram'), ('TR', 'Tripura')], max_length=100),
        ),
    ]
